version: 1.0.{build}
image: Visual Studio 2022

environment:
  NODEJS_VERSION: "20"

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - cmd: yarn install

build_script:
  - cmd: yarn lint
  - cmd: yarn test
  # - cmd: yarn test:e2e
  - cmd: yarn build

artifacts:
  - path: dist\**\*
    name: dist

build: off
